### ISSUE TITLE
When I try to save passwd in SMTP Pro, shows a blank page on Save Config

### ISSUE THREAD

**Issue by rrrohit** [aschroder/Magento-SMTP-Pro-Email-Extension#178]
Hi,

1. We have installed Magento on AWS. 
2. Enabled SMTP using SES. 
3. We have configured 2 servers on AWS in the same region (1 is a development server and the other a live server)
4. SMTP Pro is working fine on the dev server
5. But on the live server, when I try to save the password, a BLANK screen shows up
6. The following error shows in exception.log

Pls. help!

Dump from exception.log
2016-08-11T16:21:10+00:00 ERR (3): 
exception 'Zend_Mail_Protocol_Exception' with message 'Could not read from email-smtp.us-west-2.amazonaws.com' in /var/www/html/lib/Zend/Mail/Protocol/Abstract.php:385
Stack trace:
#0 /var/www/html/lib/Zend/Mail/Protocol/Abstract.php(415): Zend_Mail_Protocol_Abstract->_receive(300)
#1 /var/www/html/lib/Zend/Mail/Protocol/Smtp.php(199): Zend_Mail_Protocol_Abstract->_expect(220, 300)
#2 /var/www/html/lib/Zend/Mail/Transport/Smtp.php(200): Zend_Mail_Protocol_Smtp->helo('localhost')
#3 /var/www/html/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Smtp->_sendMail()
#4 /var/www/html/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
#5 /var/www/html/app/code/local/Aschroder/SMTPPro/Model/Email/Queue.php(99): Zend_Mail->send(Object(Zend_Mail_Transport_Smtp))
#6 [internal function]: Aschroder_SMTPPro_Model_Email_Queue->send(Object(Mage_Cron_Model_Schedule))
#7 /var/www/html/app/code/core/Mage/Cron/Model/Observer.php(326): call_user_func_array(Array, Array)
#8 /var/www/html/app/code/core/Mage/Cron/Model/Observer.php(72): Mage_Cron_Model_Observer->_processJob(Object(Mage_Cron_Model_Schedule), Object(Mage_Core_Model_Config_Element))
#9 /var/www/html/app/code/core/Mage/Core/Model/App.php(1358): Mage_Cron_Model_Observer->dispatch(Object(Varien_Event_Observer))
#10 /var/www/html/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Cron_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#11 /var/www/html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#12 /var/www/html/cron.php(78): Mage::dispatchEvent('default')
#13 {main}

**Comment by rrrohit** [comment]
I changed Mail Sending Settings in Configuration --> Advanced --> System from the AWS end-point to localhost (as was configured in my dev server), and now I am still getting a blank page but the error in the exception log is different:

NOTE: both my dev server and the live server run in the same region in AWS and as such share the same AWS/SES settings/credentials.

2016-08-11T17:40:04+00:00 ERR (3): 
exception 'Zend_Mail_Protocol_Exception' with message 'AUTH failed
' in /var/www/html/lib/Zend/Mail/Protocol/Abstract.php:431
Stack trace:
#0 /var/www/html/lib/Zend/Mail/Protocol/Smtp/Auth/Login.php(95): Zend_Mail_Protocol_Abstract->_expect(235)
#1 /var/www/html/lib/Zend/Mail/Protocol/Smtp.php(217): Zend_Mail_Protocol_Smtp_Auth_Login->auth()
#2 /var/www/html/lib/Zend/Mail/Transport/Smtp.php(200): Zend_Mail_Protocol_Smtp->helo('localhost')
#3 /var/www/html/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Smtp->_sendMail()
#4 /var/www/html/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
#5 /var/www/html/app/code/local/Aschroder/SMTPPro/Model/Email/Queue.php(99): Zend_Mail->send(Object(Zend_Mail_Transport_Smtp))
#6 [internal function]: Aschroder_SMTPPro_Model_Email_Queue->send(Object(Mage_Cron_Model_Schedule))
#7 /var/www/html/app/code/core/Mage/Cron/Model/Observer.php(326): call_user_func_array(Array, Array)
#8 /var/www/html/app/code/core/Mage/Cron/Model/Observer.php(72): Mage_Cron_Model_Observer->_processJob(Object(Mage_Cron_Model_Schedule), Object(Mage_Core_Model_Config_Element))
#9 /var/www/html/app/code/core/Mage/Core/Model/App.php(1358): Mage_Cron_Model_Observer->dispatch(Object(Varien_Event_Observer))
#10 /var/www/html/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Cron_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#11 /var/www/html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#12 /var/www/html/cron.php(78): Mage::dispatchEvent('default')
#13 {main}
