### ISSUE TITLE
Magento 1.9 

### ISSUE THREAD

**Issue by marcelmastel** [aschroder/Magento-SMTP-Pro-Email-Extension#271]
Hi, this is my exception.log if I send test email:

2019-10-22T16:47:09+00:00 ERR (3): 
exception 'Zend_Mail_Protocol_Exception' with message 'Connection refused' in /home/test/public_html/lib/Zend/Mail/Protocol/Abstract.php:277
Stack trace:
#0 /home/test/public_html/lib/Zend/Mail/Protocol/Smtp.php(167): Zend_Mail_Protocol_Abstract->_connect('-----my host-----')
#1 /home/test/public_html/lib/Zend/Mail/Transport/Smtp.php(199): Zend_Mail_Protocol_Smtp->connect()
#2 /home/test/public_html/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Smtp->_sendMail()
#3 /home/test/public_html/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
#4 /home/test/public_html/app/code/local/Aschroder/SMTPPro/controllers/Smtp/TestController.php(136): Zend_Mail->send(Object(Zend_Mail_Transport_Smtp))
#5 /home/test/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Aschroder_SMTPPro_Smtp_TestController->indexAction()
#6 /home/test/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#7 /home/test/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /home/test/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#9 /home/test/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#10 /home/test/public_html/index.php(96): Mage::run('default', 'store')
#11 {main}

**Comment by kkrieger85** [comment]
@marcelmastel 
"connection refused" seems to be a "problem" with your mailserver, not with this module. 

If you already fixed this issue, please feel free to post your solution and close this issue. 

Thanks
