### ISSUE TITLE
Catch invalid username and password in test mail

### ISSUE THREAD

**Issue by shakaran** [aschroder/Magento-SMTP-Pro-Email-Extension#70]
This is showed in var/log/exception.log if you use bad username or password in Google Apps, so Zend_Mail_Protocol_Exception should catched

```
2014-11-10T06:28:18+00:00 ERR (3): 
exception 'Zend_Mail_Protocol_Exception' with message '5.7.8 Username and Password not accepted. Learn more at
 5.7.8 http://support.google.com/mail/bin/answer.py?answer=14257 g3sm6539371qaq.35 - gsmtp
' in /var/www/html/lib/Zend/Mail/Protocol/Abstract.php:431
Stack trace:
#0 /var/www/html/lib/Zend/Mail/Protocol/Smtp/Auth/Login.php(95): Zend_Mail_Protocol_Abstract->_expect(235)
#1 /var/www/html/lib/Zend/Mail/Protocol/Smtp.php(217): Zend_Mail_Protocol_Smtp_Auth_Login->auth()
#2 /var/www/html/lib/Zend/Mail/Transport/Smtp.php(200): Zend_Mail_Protocol_Smtp->helo('localhost')
#3 /var/www/html/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Smtp->_sendMail()
#4 /var/www/html/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
#5 /var/www/html/app/code/local/Aschroder/SMTPPro/Model/Email/Template.php(106): Zend_Mail->send(Object(Zend_Mail_Transport_Smtp))
#6 /var/www/html/app/code/core/Mage/Core/Model/Email/Template.php(506): Aschroder_SMTPPro_Model_Email_Template->send(Array, Array, Array)
#7 /var/www/html/app/code/core/Mage/Core/Model/Email/Template/Mailer.php(79): Mage_Core_Model_Email_Template->sendTransactional('15', 'general', Array, Array, Array, '5')
#8 /var/www/html/app/code/core/Mage/Customer/Model/Customer.php(676): Mage_Core_Model_Email_Template_Mailer->send()
#9 /var/www/html/app/code/core/Mage/Customer/Model/Customer.php(603): Mage_Customer_Model_Customer->_sendEmailTemplate('customer/create...', 'customer/create...', Array, '5')
```

**Comment by arosiek** [comment]
got same error. any advice?

regrards

**Comment by rrrohit** [comment]
Similar issue - when I try saving the password, a blank screen appears. Any pointers? Thanks!

**Comment by aschroder** [comment]
you need to enable debug and display_errors so you can see what the actual
error is.

**Comment by rrrohit** [comment]
Where can we enable those from?

Thanks for your help.
Rohit

**Comment by sandermangel** [comment]
@rrrohit you can enable display errors in your index.php. If the issue persists please reopen this issue
