### ISSUE TITLE
Issue in Mail to a friend option

### ISSUE THREAD

**Issue by prathmanu** [aschroder/Magento-SMTP-Pro-Email-Extension#79]
I am using this extension in my e-commerce portal.Its working fine when I configure with gmail but when I configure with custom smtp email to a friend option sending mail from customer account only where as it was sending from site admin email when i set up with gmail

**Comment by aschroder** [comment]
need more info here please - screenshots of the settings, the actions
you're doing and the error or the incorrect emails etc. Also please enable
logging/debug and attach logs.

**Comment by jay-saint** [comment]
This appears to be related to issue #117 this is my error that pops up after attempting to share with friend.
```
 ERR (3): 
exception 'Zend_Mail_Protocol_Exception' with message '5.7.60 SMTP; Client does not have permissions to send as this sender
' in /chroot/home/USER/website.com/html/lib/Zend/Mail/Protocol/Abstract.php:431
Stack trace:
#0 /chroot/home/USER/website.com/html/lib/Zend/Mail/Protocol/Smtp.php(324): Zend_Mail_Protocol_Abstract->_expect(250, 600)
#1 /chroot/home/USER/website.com/html/lib/Zend/Mail/Transport/Smtp.php(215): Zend_Mail_Protocol_Smtp->data('To: =?utf-8?B?R...')
#2 /chroot/home/USER/website.com/html/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Smtp->_sendMail()
#3 /chroot/home/USER/website.com/html/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
#4 /chroot/home/USER/website.com/html/app/code/local/Aschroder/SMTPPro/Model/Email/Queue.php(99): Zend_Mail->send(Object(Zend_Mail_Transport_Smtp))
#5 [internal function]: Aschroder_SMTPPro_Model_Email_Queue->send(Object(Aoe_Scheduler_Model_Schedule))
#6 /chroot/home/USER/website.com/html/app/code/community/Aoe/Scheduler/Model/Schedule.php(184): call_user_func_array(Array, Array)
#7 /chroot/home/USER/website.com/html/app/code/community/Aoe/Scheduler/Model/Schedule.php(570): Aoe_Scheduler_Model_Schedule->runNow(true)
#8 /chroot/home/USER/website.com/html/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#9 /chroot/home/USER/website.com/html/app/code/core/Mage/Core/Model/App.php(1357): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#10 /chroot/home/USER/website.com/html/app/code/core/Mage/Core/Model/App.php(1336): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#11 /chroot/home/USER/website.com/html/app/Mage.php(456): Mage_Core_Model_App->dispatchEvent('default', Array)
#12 /chroot/home/USER/website.com/html/shell/scheduler.php(356): Mage::dispatchEvent('default', Array)
#13 /chroot/home/USER/website.com/html/shell/scheduler.php(21): Aoe_Scheduler_Shell_Scheduler->cronAction()
#14 /chroot/home/USER/website.com/html/shell/scheduler.php(382): Aoe_Scheduler_Shell_Scheduler->run()
#15 {main}
```

**Comment by aschroder** [comment]
That's coming back from your SMTP server - looks like it;s restricting the
"from:" header values. Can you try a different outbound email service?

**Comment by sysbrick** [comment]
Hello thats not the case aschoder, the problem is any server we use the module is sending the magento site user email id as the sender id to the mail server. so the smtp server will definitely reject it. How to fix it. ?

**Comment by sandermangel** [comment]
@sysbrick  Do you have any more information? I wasn't able to reproduce this issue myself but I used an smtp server with the same domain as the email address I was using as sender. And the email address was allowed to send from that SMTP
